Enhancement: Support senders name
TeskaLabs/asab-iris pull request #22
Opened 2023-05-18 04:28 UTC by mithunbharadwaj

2023-05-18 06:48 UTC, PremyslCerny approved these changes

2023-05-19 11:36 UTC, ateska approved these changes
Please extend this to To, CC and BCC in other MR.

2023-05-19 11:41 UTC, ateska requested changes

2023-05-19 11:41 UTC, ateska commented on asabiris/output/smtp/service.py
> +	def format_sender_info(self, email_info):
Extend this method to return this tuple:  
`"John Doe <johndoe@example.com>", "johndoe@example.com"`

First is "user-friendly" representation, the second is email.
The "email" will be used in `To` etc.

2023-05-22 08:46 UTC, ateska requested changes

2023-06-21 12:29 UTC, ateska approved these changes

2023-06-28 04:41 UTC, merged