Enhancement : Introduce failsafe mechanism for jinja-rendering
TeskaLabs/asab-iris pull request #33
Opened 2023-08-15 07:49 UTC by mithunbharadwaj

2023-08-22 07:59 UTC, ateska commented
That email is not very readable, honestly.

Can you please insert some newlines etc. so that is it not that "compact"?

2023-08-22 07:59 UTC, ateska requested changes

2023-08-22 08:08 UTC, mithunbharadwaj commented on asabiris/orchestration/sendemail.py
> +			error_message = "An unexpected error occurred during rendering."
@ateska yes, I can do that!

2023-08-22 10:13 UTC, ateska commented on asabiris/orchestration/sendemail.py
> +			error_message = "An unexpected error occurred during rendering."
You can either use HTML or send a plain text email ... I suggest the second option.
You need to use `\r\n` as line ends -> https://laravel.io/forum/09-04-2014-plain-text-email-line-breaks

2023-08-25 12:27 UTC, mithunbharadwaj commented on asabiris/orchestration/sendemail.py
> +			error_message = "An unexpected error occurred during rendering."
<img width="954" alt="Screenshot 2023-08-25 at 14 25 38" src="https://github.com/TeskaLabs/asab-iris/assets/17985398/426444b1-2bb0-4d9e-9ff8-ba8ad28bbf4a">

2023-08-25 12:32 UTC, ateska approved these changes

2023-08-26 07:03 UTC, ateska approved these changes

2023-08-26 07:03 UTC, ateska commented on asabiris/app.py
> +	"smtp": {
this should be:

```
[jinja]
failsafe=True
```

2023-08-28 08:45 UTC, merged