Load variables from json file
TeskaLabs/asab-iris pull request #41
Opened 2023-10-30 08:44 UTC by mithunbharadwaj

2023-10-31 10:38 UTC, ateska requested changes
Please, send me also the output of the test: jinja template with lower case, upper case and mixed case of the jinja parameter, the input dictionary and the output.

thanks.

2023-10-31 10:38 UTC, ateska commented on asabiris/formatter/jinja/service.py
> +        template_params = utils.create_nested_dict_from_dots_in_keys(jinja_variables)
Is it tested?

I see that you prepared that `__getitem__` method.
But you are not applying that anywhere.

How do you apply that on `template_params`?

I guess you need to create some kind of wrapper class.

2023-11-13 20:01 UTC, ateska commented
Only case-insensitive dictionary wrapper for Jinja2 is needed here, due to https://github.com/TeskaLabs/asab-iris/pull/43

But b/c the code switched from tabs to spaces, it is difficult to isolate the actual implementation.

2023-11-13 21:57 UTC, ateska commented
Please close this one and implement json loading in https://github.com/TeskaLabs/asab-iris/pull/43

2023-11-16 08:09 UTC, mithunbharadwaj commented
Closing this MR. Solving here (https://github.com/TeskaLabs/asab-iris/pull/45)

2023-11-16 08:09 UTC, closed without merging