Make slack service failsafe
TeskaLabs/asab-iris pull request #56
Opened 2023-12-12 09:27 UTC by mithunbharadwaj

2023-12-13 13:30 UTC, eliska-n requested changes

2023-12-13 13:30 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +		try:
No, Mithun, no "except Exception" on my watch. You must try harder.

2023-12-13 13:30 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +			await self.SlackOutputService.send_message(blocks, error_message)
what if the exception comes from sending the message? then, you send another message which does not reach its target and you return 200 in response?

That's not a good approach

2023-12-13 13:30 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +			# Sending attachments
can you send a message with attachment? or is it either mesage or attachment without message?

2023-12-13 13:30 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +			"We encountered an issue while processing your request:\n`{}`\n\n"
You want to send the specific error to the end user (customer!) only if they can do something about that. If it says there is wrong configuration if the BE service (for example), it is not helpful.

2023-12-13 13:30 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +		try:
You must sort the exceptions.

2023-12-13 13:35 UTC, eliska-n requested changes

2023-12-13 13:35 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +			output = await self.JinjaService.format(template, params)
this is string

2023-12-13 13:35 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +					fallback_message = output
this is string

2023-12-13 13:35 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +				await self.SlackOutputService.send_message(blocks, fallback_message)
here the second argument is string

2023-12-13 13:35 UTC, eliska-n commented on asabiris/orchestration/sendslack.py
> +	def _generate_error_message_slack(self, specific_error: str) -> Tuple[str, str]:
this does not return tuple, am I right? You copypasted this from some copilot or chatgpt without reviewing the code

2024-01-11 11:50 UTC, ateska commented
No, this is nonsense ... "failsafe", "exception_manager" ... I completely don't get this.

2024-01-16 16:01 UTC, ateska commented
This MR will be closed - after discussion - and another mechanism for error handling and forward fail-safe will be introduced.

2024-02-02 10:37 UTC, closed without merging