Add default kafka config
TeskaLabs/asab-iris pull request #59
Opened 2024-01-23 17:46 UTC by eliska-n

Config for maestro. Default topic is `asab-notifications`. It cannot be `lmio-notifications` within asab service.

2024-01-24 12:12 UTC, mithunbharadwaj approved these changes

2024-01-25 16:44 UTC, ateska requested changes

2024-01-25 16:44 UTC, ateska commented on asabiris/app.py
> +		"topic": "asab-notifications",
`notifications` ?

2024-02-01 12:10 UTC, eliska-n commented on asabiris/app.py
> +		"topic": "asab-notifications",
sure

2024-02-07 12:30 UTC, ateska approved these changes

2024-03-20 12:26 UTC, merged